name: Deploy to One.com (Main Only)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ssh.cj17qpctg.service.one
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22  # Port SFTP
          source: "."
          target: "/customers/e/e/e/cj17qpctg/webroots/68c504e6"
          strip_components: 0
          overwrite: true
          target_remove: false
          dry-run: false  # Vérifie d'abord avec true si besoin
          log-level: verbose  # Affiche en détail ce qui est uploadé