name: Deploy to One.com (Master Only)

on:
  push:
    branches:
      - master  # Déploiement uniquement sur la branche master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ssh.cj17qpctg.service.one
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /customers/e/e/e/cj17qpctg/webroots/68c504e6/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules*
            **/.env*